/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
<#if  language == "kotlin">
buildscript {
  ext {
    kotlinVersion = '1.2.60'
  }

  repositories {
    mavenCentral()
  }

  dependencies {
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
  }
}
</#if>
plugins {
  id 'java'
  id 'application'
  id 'com.github.johnrengelman.shadow' version '2.0.4'
}
<#if  language == "kotlin">
apply plugin: 'kotlin'
</#if>
ext {
<#if  language == "kotlin">
  kotlinVersion = '1.2.60'
</#if>
  vertxVersion = '${vertxVersion}'
  junitJupiterEngineVersion = '5.2.0'
}

repositories {
  mavenLocal()
  jcenter()
}

group = '${groupId}'
version = '1.0.0-SNAPSHOT'

sourceCompatibility = '1.8'
mainClassName = 'io.vertx.core.Launcher'

def mainVerticleName = '${groupId}.${artifactId}.MainVerticle'
def watchForChange = 'src/**/*'
def doOnChange = './gradlew classes'

dependencies {
<#if  language == "kotlin">
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion"
</#if>

  implementation "io.vertx:vertx-core:$vertxVersion"
<#list vertxDependencies as dependency>
  implementation "io.vertx:${dependency}:$vertxVersion"
</#list>

  testImplementation "io.vertx:vertx-junit5:$vertxVersion"
  testRuntime("org.junit.jupiter:junit-jupiter-engine:$junitJupiterEngineVersion")
}

<#if  language == "kotlin">
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
  kotlinOptions {
    jvmTarget = "1.8"
  }
}
</#if>

shadowJar {
  classifier = 'fat'
  manifest {
    attributes 'Main-Verticle': mainVerticleName
  }
  mergeServiceFiles {
    include 'META-INF/services/io.vertx.core.spi.VerticleFactory'
  }
}

test {
  useJUnitPlatform()
  testLogging {
    events 'PASSED', 'FAILED', 'SKIPPED'
  }
}

run {
  args = ['run', mainVerticleName, "--redeploy=$watchForChange", "--launcher-class=$mainClassName", "--on-redeploy=$doOnChange"]
}

task wrapper(type: Wrapper) {
  gradleVersion = '4.6'
}
